version: "3"

services:
  openwebui-telegram:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: realsidsun/openwebui-telegram:latest
    volumes:
      - ./data/store:/app/store
      - ./data/config:/app/config
    network_mode: host
    restart: unless-stopped
